version: '3.7'

services:
  MySQLDockerContainer:
    container_name: MySQLDockerContainer
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: IMSEMS2
      MYSQL_DATABASE: IMSE_MS2
      MYSQL_ROOT_HOST: '%' 
    ports:
      - "6000:3306"
    volumes:
      - ./src:/var/www/html
      - ./MySQL-init:/docker-entrypoint-initdb.d
    networks:
    - IMSEDockerNetwork

  MyAdminer:
    container_name: MyAdminer
    image: adminer:latest
    depends_on:
      - MySQLDockerContainer
    environment:
      ADMINER_DEFAULT_SERVER: MySQLDockerContainer
    ports:
      - "6080:8080"
    networks:
    - IMSEDockerNetwork

  MyMongoDBContainer:
    container_name: MyMongoDBContainer
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: Irdi
      MONGO_INITDB_ROOT_PASSWORD: Password1
    volumes:
      - mongo-data:/data/db
    ports:
      - "27018:27017"
    networks:
    - IMSEDockerNetwork

  MyMongoDBExpress:
    container_name: MyMongoDBExpress
    image: mongo-express:latest
    depends_on:
      - MyMongoDBContainer
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Irdi
      ME_CONFIG_MONGODB_ADMINPASSWORD: Password1
      ME_CONFIG_MONGODB_SERVER: MyMongoDBContainer
    ports:
      - "6081:8081"
    networks:
    - IMSEDockerNetwork

  php-app:
      build:
        context: .
      container_name: php-app-container
      ports:
        - "6060:80"
      networks:
        - IMSEDockerNetwork

networks:
  IMSEDockerNetwork:

volumes:
  mysql-data:
  mongo-data: